"""Stable public vocabulary for safety decisions and categories."""

from enum import StrEnum


class SafetyDecision(StrEnum):
    ALLOW = "ALLOW"
    ALLOW_WITH_NOTICE = "ALLOW_WITH_NOTICE"
    WARN = "WARN"
    BLOCK = "BLOCK"
    ESCALATE = "ESCALATE"


class SafetyCategory(StrEnum):
    URGENT_SYMPTOM = "URGENT_SYMPTOM"
    MEDICATION_CHANGE = "MEDICATION_CHANGE"
    DIAGNOSIS_REQUEST = "DIAGNOSIS_REQUEST"
    PRESCRIBING_REQUEST = "PRESCRIBING_REQUEST"
    UNSUPPORTED_CURE_CLAIM = "UNSUPPORTED_CURE_CLAIM"
    TREATMENT_REPLACEMENT = "TREATMENT_REPLACEMENT"
    HIGH_RISK_SELF_TREATMENT = "HIGH_RISK_SELF_TREATMENT"
    GENERAL_HEALTH_INFORMATION = "GENERAL_HEALTH_INFORMATION"
    LOGGING_ONLY = "LOGGING_ONLY"
    UNKNOWN = "UNKNOWN"
