"""create phase 2 core schema

Revision ID: c7171adadddb
Revises:
Create Date: 2026-09-12 22:04:51.080537
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "c7171adadddb"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_username"), ["username"], unique=True)

    op.create_table(
        "audit_logs",
        sa.Column("actor_user_id", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=False),
        sa.Column("before_state", sa.JSON(), nullable=True),
        sa.Column("after_state", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index("ix_audit_entity", ["entity_type", "entity_id"], unique=False)

    op.create_table(
        "health_profiles",
        sa.Column("owner_user_id", sa.String(length=36), nullable=False),
        sa.Column("display_name", sa.String(length=150), nullable=False),
        sa.Column(
            "relationship_to_owner",
            sa.Enum(
                "SELF",
                "MOTHER",
                "FATHER",
                "SIBLING",
                "CHILD",
                "GRANDMOTHER",
                "GRANDFATHER",
                "OTHER",
                name="relationshiptype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("sex", sa.String(length=50), nullable=True),
        sa.Column(
            "access_level",
            sa.Enum(
                "PRIVATE",
                "CAREGIVER",
                "FAMILY_SUMMARY",
                "FULL",
                name="accesslevel",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("health_profiles", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_health_profiles_owner_user_id"), ["owner_user_id"], unique=False
        )

    op.create_table(
        "consent_permissions",
        sa.Column("profile_id", sa.String(length=36), nullable=False),
        sa.Column("grantee_user_id", sa.String(length=36), nullable=True),
        sa.Column("grantee_profile_id", sa.String(length=36), nullable=True),
        sa.Column(
            "access_level",
            sa.Enum(
                "PRIVATE",
                "CAREGIVER",
                "FAMILY_SUMMARY",
                "FULL",
                name="accesslevel",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("scope", sa.String(length=250), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "grantee_user_id IS NOT NULL OR grantee_profile_id IS NOT NULL",
            name="ck_permission_has_grantee",
        ),
        sa.ForeignKeyConstraint(
            ["grantee_profile_id"],
            ["health_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["grantee_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["health_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("consent_permissions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_consent_permissions_profile_id"), ["profile_id"], unique=False
        )

    op.create_table(
        "conversations",
        sa.Column("profile_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=250), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["health_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_conversations_profile_id"), ["profile_id"], unique=False
        )

    op.create_table(
        "family_relationships",
        sa.Column("source_profile_id", sa.String(length=36), nullable=False),
        sa.Column("target_profile_id", sa.String(length=36), nullable=False),
        sa.Column(
            "relationship_type",
            sa.Enum(
                "SELF",
                "MOTHER",
                "FATHER",
                "SIBLING",
                "CHILD",
                "GRANDMOTHER",
                "GRANDFATHER",
                "OTHER",
                name="relationshiptype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.CheckConstraint(
            "source_profile_id != target_profile_id", name="ck_family_distinct_profiles"
        ),
        sa.ForeignKeyConstraint(
            ["source_profile_id"],
            ["health_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_profile_id"],
            ["health_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_profile_id",
            "target_profile_id",
            "relationship_type",
            name="uq_family_relationship",
        ),
    )
    op.create_table(
        "source_documents",
        sa.Column("profile_id", sa.String(length=36), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("stored_filename", sa.String(length=255), nullable=False),
        sa.Column("mime_type", sa.String(length=150), nullable=False),
        sa.Column("file_hash", sa.String(length=128), nullable=True),
        sa.Column("storage_path", sa.String(length=500), nullable=False),
        sa.Column("document_date", sa.Date(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "VERIFIED",
                "REJECTED",
                "NEEDS_REVIEW",
                name="verificationstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("extracted_text", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["health_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stored_filename"),
    )
    with op.batch_alter_table("source_documents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_source_documents_profile_id"), ["profile_id"], unique=False
        )

    op.create_table(
        "extracted_candidates",
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("candidate_type", sa.String(length=100), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("structured_data", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "ACCEPTED",
                "CORRECTED",
                "REJECTED",
                "NEEDS_CLARIFICATION",
                name="candidatestatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("reviewed_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["source_documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("extracted_candidates", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_extracted_candidates_document_id"), ["document_id"], unique=False
        )

    op.create_table(
        "health_events",
        sa.Column("profile_id", sa.String(length=36), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "CONDITION",
                "MEDICATION",
                "LAB",
                "PROCEDURE",
                "SYMPTOM",
                "MEASUREMENT",
                "HOSPITALIZATION",
                "ALLERGY",
                "IMMUNIZATION",
                "LIFESTYLE",
                "FAMILY_HISTORY",
                "NOTE",
                name="healtheventtype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("event_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "verification_status",
            sa.Enum(
                "PENDING",
                "VERIFIED",
                "REJECTED",
                "NEEDS_REVIEW",
                name="verificationstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "provenance",
            sa.Enum(
                "DOCUMENT_VERIFIED",
                "USER_REPORTED",
                "DEVICE_MEASURED",
                "AI_EXTRACTED",
                "AI_DERIVED",
                "USER_CORRECTED",
                name="provenancetype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("source_document_id", sa.String(length=36), nullable=True),
        sa.Column("created_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["health_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["source_documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("health_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_health_events_profile_date", ["profile_id", "event_date"], unique=False
        )

    op.create_table(
        "messages",
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column(
            "role",
            sa.Enum("USER", "ASSISTANT", "SYSTEM", name="messagerole", native_enum=False),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.create_index(
            "ix_messages_conversation_created", ["conversation_id", "created_at"], unique=False
        )

    op.create_table(
        "medications",
        sa.Column("profile_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=250), nullable=False),
        sa.Column("dose", sa.String(length=100), nullable=True),
        sa.Column("dose_unit", sa.String(length=50), nullable=True),
        sa.Column("frequency", sa.String(length=100), nullable=True),
        sa.Column("route", sa.String(length=100), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "provenance",
            sa.Enum(
                "DOCUMENT_VERIFIED",
                "USER_REPORTED",
                "DEVICE_MEASURED",
                "AI_EXTRACTED",
                "AI_DERIVED",
                "USER_CORRECTED",
                name="provenancetype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "verification_status",
            sa.Enum(
                "PENDING",
                "VERIFIED",
                "REJECTED",
                "NEEDS_REVIEW",
                name="verificationstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("source_event_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["health_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_event_id"],
            ["health_events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("medications", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_medications_profile_id"), ["profile_id"], unique=False)

    op.create_table(
        "observations",
        sa.Column("profile_id", sa.String(length=36), nullable=False),
        sa.Column("health_event_id", sa.String(length=36), nullable=True),
        sa.Column("code", sa.String(length=100), nullable=True),
        sa.Column("display_name", sa.String(length=250), nullable=False),
        sa.Column("value_number", sa.Float(), nullable=True),
        sa.Column("value_text", sa.String(length=500), nullable=True),
        sa.Column("unit", sa.String(length=50), nullable=True),
        sa.Column("reference_low", sa.Float(), nullable=True),
        sa.Column("reference_high", sa.Float(), nullable=True),
        sa.Column("interpretation", sa.String(length=250), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "provenance",
            sa.Enum(
                "DOCUMENT_VERIFIED",
                "USER_REPORTED",
                "DEVICE_MEASURED",
                "AI_EXTRACTED",
                "AI_DERIVED",
                "USER_CORRECTED",
                name="provenancetype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "verification_status",
            sa.Enum(
                "PENDING",
                "VERIFIED",
                "REJECTED",
                "NEEDS_REVIEW",
                name="verificationstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "value_number IS NOT NULL OR value_text IS NOT NULL", name="ck_observation_has_value"
        ),
        sa.ForeignKeyConstraint(
            ["health_event_id"],
            ["health_events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["health_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("observations", schema=None) as batch_op:
        batch_op.create_index(
            "ix_observations_profile_observed", ["profile_id", "observed_at"], unique=False
        )

    op.create_table(
        "symptoms",
        sa.Column("profile_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=250), nullable=False),
        sa.Column("severity", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "provenance",
            sa.Enum(
                "DOCUMENT_VERIFIED",
                "USER_REPORTED",
                "DEVICE_MEASURED",
                "AI_EXTRACTED",
                "AI_DERIVED",
                "USER_CORRECTED",
                name="provenancetype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "verification_status",
            sa.Enum(
                "PENDING",
                "VERIFIED",
                "REJECTED",
                "NEEDS_REVIEW",
                name="verificationstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("source_event_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["health_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_event_id"],
            ["health_events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("symptoms", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_symptoms_profile_id"), ["profile_id"], unique=False)

    op.create_table(
        "evidence_links",
        sa.Column("health_event_id", sa.String(length=36), nullable=True),
        sa.Column("observation_id", sa.String(length=36), nullable=True),
        sa.Column("source_document_id", sa.String(length=36), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("source_excerpt", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.CheckConstraint(
            "health_event_id IS NOT NULL OR observation_id IS NOT NULL",
            name="ck_evidence_has_target",
        ),
        sa.ForeignKeyConstraint(
            ["health_event_id"],
            ["health_events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["observations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["source_documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("evidence_links", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_evidence_links_source_document_id"), ["source_document_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverse this schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("evidence_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_evidence_links_source_document_id"))

    op.drop_table("evidence_links")
    with op.batch_alter_table("symptoms", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_symptoms_profile_id"))

    op.drop_table("symptoms")
    with op.batch_alter_table("observations", schema=None) as batch_op:
        batch_op.drop_index("ix_observations_profile_observed")

    op.drop_table("observations")
    with op.batch_alter_table("medications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_medications_profile_id"))

    op.drop_table("medications")
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index("ix_messages_conversation_created")

    op.drop_table("messages")
    with op.batch_alter_table("health_events", schema=None) as batch_op:
        batch_op.drop_index("ix_health_events_profile_date")

    op.drop_table("health_events")
    with op.batch_alter_table("extracted_candidates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_extracted_candidates_document_id"))

    op.drop_table("extracted_candidates")
    with op.batch_alter_table("source_documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_source_documents_profile_id"))

    op.drop_table("source_documents")
    op.drop_table("family_relationships")
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversations_profile_id"))

    op.drop_table("conversations")
    with op.batch_alter_table("consent_permissions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_consent_permissions_profile_id"))

    op.drop_table("consent_permissions")
    with op.batch_alter_table("health_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_health_profiles_owner_user_id"))

    op.drop_table("health_profiles")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_entity")

    op.drop_table("audit_logs")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))

    op.drop_table("users")
    # ### end Alembic commands ###
